[package]
name = "cubeos-service"
version = "0.2.0"
authors = ["Patrick Oppel <patrick.oppel94@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
log = "^0.4.0"
# Pinning this to 0.3.15 due to kubos linux build issues with v0.3.16
pkg-config = "= 0.3.15"

kubos-system = { git = "ssh://git@github.com/Cube-OS/system-api.git"}
cubeos-error = { git = "ssh://git@github.com/Cube-OS/cubeos-error.git"}
bincode = { git = "ssh://git@github.com/Cube-OS/bincode.git"}
command-id = { git = "ssh://git@github.com/Cube-OS/command-id.git"}
rust-udp = { git = "ssh://git@github.com/Cube-OS/rust-udp"}
dialoguer = "0.10.2"
strum = "0.24"
strum_macros = "0.24"

# features enable conditional compiling,
# features cannot be combined in one compilation
[features]
default = []
ground = []
# all features can be combined with debug
debug = []
