[package]
name = "cubeos-service"
version = "0.1.0"
authors = ["Patrick Oppel <patrick.oppel94@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_repr = "0.1"
# Freezing this at 0.14.2 for now, future update could require major changes
juniper = "0.14.2"
juniper_warp = "0.5.2"
kubos-system = { git = "ssh://git@github.com/Cube-OS/system-api.git"}
log = "^0.4.0"
warp = "0.1.23"
# Pinning this to 0.3.15 due to kubos linux build issues with v0.3.16
pkg-config = "= 0.3.15"
failure = "0.1.3"
variant_count = "1.1"
cubeos-error = { git = "ssh://git@github.com/Cube-OS/cubeos-error.git"}
bincode = { git = "ssh://git@github.com/Cube-OS/bincode.git"}
hex = "0.4.2"
command-id = { git = "ssh://git@github.com/Cube-OS/command-id.git"}

# features enable conditional compiling,
# features cannot be combined in one compilation
[features]
default = []
ground = []
graphql = []
# all features can be combined with debug
debug = []
