[package]
name = "cubeos-service"
version = "0.2.0"
authors = ["Patrick Oppel <patrick.oppel94@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
log = "^0.4.0"
# Pinning this to 0.3.15 due to kubos linux build issues with v0.3.16
pkg-config = "= 0.3.15"

kubos-system = { git = "ssh://git@github.com/Cube-OS/system-api.git"}
cubeos-error = { git = "ssh://git@github.com/Cube-OS/cubeos-error.git"}
bincode = { git = "ssh://git@github.com/Cube-OS/bincode.git"}
command-id = { git = "ssh://git@github.com/Cube-OS/command-id.git"}
rust-udp = { git = "ssh://git@github.com/Cube-OS/rust-udp"}

# Freezing this at 0.14.2 for now, future update could require major changes
juniper = { version = "0.14.2", optional = true }
juniper_warp = {version = "0.5.2", optional = true }
warp = {version = "0.1.23", optional = true }

# features enable conditional compiling,
# features cannot be combined in one compilation
[features]
default = []
ground = ["dep:juniper","dep:juniper_warp","dep:warp"]
# all features can be combined with debug
debug = []
